# Generated by Django 3.0.4 on 2020-03-28 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200328_1855'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ram',
            table='app_t_ram',
        ),
    ]
