# Generated by Django 3.0.4 on 2020-03-28 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200328_1856'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ram',
            table='RAM',
        ),
    ]
