# Generated by Django 3.0.4 on 2020-03-28 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200328_1904'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ram',
            table='app_ram',
        ),
    ]
