# Generated by Django 3.0.4 on 2020-03-28 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200328_1910'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ram',
            table='RAM_2',
        ),
    ]
