# Generated by Django 3.0.4 on 2020-03-28 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200328_1911'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ram',
            table='RAM_3',
        ),
    ]
