# Generated by Django 3.0.4 on 2020-03-28 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200328_1912'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ram',
            table='app_ram_2',
        ),
    ]
